<?php
/**
 * @copyright: Copyright © 2017 Firebear Studio. All rights reserved.
 * @author   : Firebear Studio <fbeardev@gmail.com>
 */

/**@var \Magento\Backend\Block\Widget\Form\Renderer\Fieldset $block */
?>
<?php $_element = $block->getElement() ?>
<?php $_jsObjectName = $block->getFieldSetId() != null ? $block->getFieldSetId() : $_element->getHtmlId() ?>
<?php $_jsObjectName .= '__recordId__' ?>
<div class="price-rule-tree rule-tree">
    <div id="<?= /** @noEscape */ $_jsObjectName ?>" <?= /** @noEscape */ $_element->serialize(['class']) ?>>
        <?php if ($_element->getComment()): ?>
            <div class="messages">
                <div class="message message-notice"><?= $block->escapeHtml($_element->getComment()) ?></div>
            </div>
        <?php endif; ?>
        <div class="rule-tree-wrapper">
            <?= $_element->getChildrenHtml() ?>
        </div>
    </div>
</div>

<script>
    require([
        "Firebear_ImportExport/js/rules",
        "prototype"
    ], function(VarienRulesForm){

        window.<?= /** @noEscape */ $_jsObjectName ?> = new VarienRulesForm(
            '<?= /** @noEscape */ $_jsObjectName ?>',
            '<?= /** @noEscape */ $block->getNewChildUrl() ?>',
            '__recordId__'
        );
        <?php if ($_element->getReadonly()): ?>
            <?= $_element->getHtmlId() ?>.setReadonly(true);
        <?php endif; ?>

    });
</script>
