<?php
/**
 * @copyright: Copyright © 2017 Firebear Studio. All rights reserved.
 * @author   : Firebear Studio <fbeardev@gmail.com>
 */
/**
 * @var Firebear\ImportExport\Block\Adminhtml\Import\History\Before $block
 */
?>
<div id="messages">
    <div class="messages">
        <div class="message message-notice">
            <div>
                <?= /** @noEscape */ __(
                    'You have installed and enabled FireBear Studio Improved Import / Export extension - '.
                    'to use it please go to System -> %1 / %2. We don\'t improve and not make any changes on '.
                    'default Magento 2 Import / Export behaviour!',
                    '<a href="' .$block->url->getUrl('import/job/index') .'">Import Jobs</a>',
                    '<a href="' .$block->url->getUrl('import/export_job/index') .'">Export Jobs</a>'
                ); ?>
            </div>
        </div>
    </div>
</div>
